#!/usr/bin/env python3
"""
build_rsz_db.py — Preprocessor for RE9 RSZ type database
Converts rszre9.json (44MB) and re9_enums.json (3MB) into compact Lua modules
that can be loaded at runtime without freezing the game.

Usage:
    python tools/build_rsz_db.py

Input:
    deploy/rszre9.json       — Full RSZ type dump (type hash → class + fields)
    deploy/re9_enums.json    — Enum definitions (type name → value/name pairs)

Output:
    deploy/requiem_trainer/emv_engine/rsz_types.lua   (~500KB)
    deploy/requiem_trainer/emv_engine/rsz_enums.lua   (~200KB)
"""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
DEPLOY_DIR = os.path.join(ROOT_DIR, "deploy")
OUTPUT_DIR = os.path.join(DEPLOY_DIR, "requiem_trainer", "emv_engine")

RSZ_JSON = os.path.join(DEPLOY_DIR, "rszre9.json")
ENUM_JSON = os.path.join(DEPLOY_DIR, "re9_enums.json")

# Prefixes of types to include (must have non-empty fields)
INCLUDE_PREFIXES = (
    "app.",
    "via.",
    "anim.",
)

# Prefixes to always skip even if they match above
SKIP_PREFIXES = (
    "System.Collections.",
    "System.Array.",
    "System.Linq.",
    "System.Runtime.",
    "System.Threading.",
    "System.Reflection.",
    "System.Converter",
    "System.Func",
    "System.Action",
    "System.Predicate",
    "System.Comparison",
)


def lua_escape(s: str) -> str:
    """Escape a string for Lua string literals."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "")


def build_types():
    """Read rszre9.json and produce rsz_types.lua."""
    print(f"Reading {RSZ_JSON}...")
    with open(RSZ_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Filter: only types with fields, matching our prefixes
    types = {}
    for key, entry in data.items():
        if key == "metadata":
            continue
        name = entry.get("name", "")
        if not name:
            continue

        # Must start with an included prefix
        if not any(name.startswith(p) for p in INCLUDE_PREFIXES):
            continue

        # Skip noise types
        if any(name.startswith(p) for p in SKIP_PREFIXES):
            continue

        # Skip generic types with angle brackets (List`1, Dictionary`2, etc.)
        if "`" in name or "<" in name:
            continue

        fields = entry.get("fields", [])
        if not fields:
            continue

        # Skip types that only have a single "value__" field (bare enums)
        if len(fields) == 1 and fields[0].get("name") == "value__":
            continue

        parent = entry.get("parent", "")
        types[name] = {"parent": parent, "fields": fields}

    print(f"  Found {len(types)} types with fields (from {len(data)} total entries)")

    # Write Lua module
    out_path = os.path.join(OUTPUT_DIR, "rsz_types.lua")
    print(f"Writing {out_path}...")

    lines = []
    lines.append("-- AUTO-GENERATED by tools/build_rsz_db.py — DO NOT EDIT")
    lines.append(f"-- {len(types)} RE9 types with field definitions")
    lines.append("-- Source: deploy/rszre9.json")
    lines.append("return {")

    for name in sorted(types.keys()):
        t = types[name]
        ename = lua_escape(name)
        lines.append(f'["{ename}"] = {{')

        if t["parent"]:
            lines.append(f'  parent = "{lua_escape(t["parent"])}",')

        lines.append("  fields = {")
        for f in t["fields"]:
            fname = lua_escape(f.get("name", ""))
            ftype = f.get("type", "?")
            orig = lua_escape(f.get("original_type", ""))
            is_array = "true" if f.get("array", False) else "false"
            size = f.get("size", 0)
            lines.append(
                f'    {{name="{fname}", type="{ftype}", orig="{orig}", array={is_array}, size={size}}},'
            )
        lines.append("  },")
        lines.append("},")

    lines.append("}")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    size_kb = os.path.getsize(out_path) / 1024
    print(f"  Written {size_kb:.0f} KB ({len(types)} types)")
    return len(types)


def build_enums():
    """Read re9_enums.json and produce rsz_enums.lua."""
    print(f"Reading {ENUM_JSON}...")
    with open(ENUM_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Filter: only enums with reasonable sizes (skip huge ID ranges)
    enums = {}
    for name, values in data.items():
        if not isinstance(values, list):
            continue
        # Skip enums with more than 256 values (noise like LogId)
        if len(values) > 256:
            continue
        # Must have at least one value
        if not values:
            continue
        enums[name] = values

    print(f"  Found {len(enums)} enums (from {len(data)} total)")

    out_path = os.path.join(OUTPUT_DIR, "rsz_enums.lua")
    print(f"Writing {out_path}...")

    lines = []
    lines.append("-- AUTO-GENERATED by tools/build_rsz_db.py — DO NOT EDIT")
    lines.append(f"-- {len(enums)} RE9 enum definitions")
    lines.append("-- Source: deploy/re9_enums.json")
    lines.append("return {")

    for name in sorted(enums.keys()):
        values = enums[name]
        ename = lua_escape(name)
        lines.append(f'["{ename}"] = {{')
        for v in values:
            vname = lua_escape(v.get("name", "?"))
            vval = v.get("value", 0)
            lines.append(f'  [{vval}] = "{vname}",')
        lines.append("},")

    lines.append("}")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    size_kb = os.path.getsize(out_path) / 1024
    print(f"  Written {size_kb:.0f} KB ({len(enums)} enums)")
    return len(enums)


if __name__ == "__main__":
    print("=" * 60)
    print("RE9 RSZ Database Preprocessor")
    print("=" * 60)

    if not os.path.exists(RSZ_JSON):
        print(f"ERROR: {RSZ_JSON} not found!")
        sys.exit(1)
    if not os.path.exists(ENUM_JSON):
        print(f"ERROR: {ENUM_JSON} not found!")
        sys.exit(1)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    n_types = build_types()
    print()
    n_enums = build_enums()

    print()
    print("=" * 60)
    print(f"Done! {n_types} types, {n_enums} enums")
    print("=" * 60)
